
server:
  port: 9527
spring:
  application:
    name: 06-cloud-gateway-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-eureka-client-payment-service   #匹配8001提供服务的路由地址

          predicates:
            #- Path=/payment/get/**   #断言,路径相匹配的进行路由
            - Path=/payment/lb/**
            - After=2021-01-10T18:03:46.693+08:00[Asia/Shanghai] #设置执行时间，After 时间
            - Before=2021-09-10T18:03:46.693+08:00[Asia/Shanghai] #设置执行时间，Before 时间
            - Between=2021-01-10T10:59:34.102+08:00[Asia/Shanghai] , 2021-09-10T10:59:34.102+08:00[Asia/Shanghai] #设置执行时间，Between 时间
#           - Cookie=username,LanLinxiang
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由



        - id: payment_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
            uri: lb://cloud-eureka-client-payment-service   #匹配8001提供服务的路由地址

            predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由










eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    register-with-eureka: true     #true表示向注册中心注册自己。
    fetchregistry: true     #true 表示去检索服务
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/




  #设置OpenFeign的日志打印级别
logging:
  level:
    com.llx.springcloud.service.OrderService: debug



