#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.12.131:3306/llx_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driverClassName: com.mysql.cj.jdbc.Driver
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: llxmall-product
#
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
logging:
  level:
    com.llx.llxmall: debug
